<?php

use Toybox\Core\Components\Customizer;

?>
<style>
    :root {
        --color-primary-1:       <?= ! empty(Customizer::get("toybox_color_primary_1"))                     ? Customizer::get("toybox_color_primary_1")                     : "#000"                                                                                                                                                                                                            ?>;
        --color-primary-2:       <?= ! empty(Customizer::get("toybox_color_primary_2"))                     ? Customizer::get("toybox_color_primary_2")                     : "#000"                                                                                                                                                                                                            ?>;
        --color-primary-3:       <?= ! empty(Customizer::get("toybox_color_primary_3"))                     ? Customizer::get("toybox_color_primary_3")                     : "#000"                                                                                                                                                                                                            ?>;
        --color-primary-4:       <?= ! empty(Customizer::get("toybox_color_primary_4"))                     ? Customizer::get("toybox_color_primary_4")                     : "#000"                                                                                                                                                                                                            ?>;
        --color-secondary-1:     <?= ! empty(Customizer::get("toybox_color_secondary_1"))                   ? Customizer::get("toybox_color_secondary_1")                   : "#000"                                                                                                                                                                                                            ?>;
        --color-secondary-2:     <?= ! empty(Customizer::get("toybox_color_secondary_2"))                   ? Customizer::get("toybox_color_secondary_2")                   : "#000"                                                                                                                                                                                                            ?>;
        --color-secondary-3:     <?= ! empty(Customizer::get("toybox_color_secondary_3"))                   ? Customizer::get("toybox_color_secondary_3")                   : "#000"                                                                                                                                                                                                            ?>;
        --color-secondary-4:     <?= ! empty(Customizer::get("toybox_color_secondary_4"))                   ? Customizer::get("toybox_color_secondary_4")                   : "#000"                                                                                                                                                                                                            ?>;
        --color-tertiary-1:      <?= ! empty(Customizer::get("toybox_color_tertiary_1"))                    ? Customizer::get("toybox_color_tertiary_1")                    : "#000"                                                                                                                                                                                                            ?>;
        --color-tertiary-2:      <?= ! empty(Customizer::get("toybox_color_tertiary_2"))                    ? Customizer::get("toybox_color_tertiary_2")                    : "#000"                                                                                                                                                                                                            ?>;
        --color-tertiary-3:      <?= ! empty(Customizer::get("toybox_color_tertiary_3"))                    ? Customizer::get("toybox_color_tertiary_3")                    : "#000"                                                                                                                                                                                                            ?>;
        --color-tertiary-4:      <?= ! empty(Customizer::get("toybox_color_tertiary_4"))                    ? Customizer::get("toybox_color_tertiary_4")                    : "#000"                                                                                                                                                                                                            ?>;
        --color-quaternary-1:    <?= ! empty(Customizer::get("toybox_color_quaternary_1"))                  ? Customizer::get("toybox_color_quaternary_1")                  : "#000"                                                                                                                                                                                                            ?>;
        --color-quaternary-2:    <?= ! empty(Customizer::get("toybox_color_quaternary_2"))                  ? Customizer::get("toybox_color_quaternary_2")                  : "#000"                                                                                                                                                                                                            ?>;
        --color-quaternary-3:    <?= ! empty(Customizer::get("toybox_color_quaternary_3"))                  ? Customizer::get("toybox_color_quaternary_3")                  : "#000"                                                                                                                                                                                                            ?>;
        --color-quaternary-4:    <?= ! empty(Customizer::get("toybox_color_quaternary_4"))                  ? Customizer::get("toybox_color_quaternary_4")                  : "#000"                                                                                                                                                                                                            ?>;
        --h1-size-full:          <?= ! empty(Customizer::get("toybox_headings_h1_size_full"))               ? Customizer::get("toybox_headings_h1_size_full")               : 2.5                                                                                                                                                                                                               ?>rem;
        --h1-size-medium:        <?= ! empty(Customizer::get("toybox_headings_h1_size_medium"))             ? Customizer::get("toybox_headings_h1_size_medium")             : 2.25                                                                                                                                                                                                              ?>rem;
        --h1-size-small:         <?= ! empty(Customizer::get("toybox_headings_h1_size_small"))              ? Customizer::get("toybox_headings_h1_size_small")              : 2                                                                                                                                                                                                                 ?>rem;
        --h1-weight:             <?= ! empty(Customizer::get("toybox_headings_h1_weight"))                  ? Customizer::get("toybox_headings_h1_weight")                  : 600                                                                                                                                                                                                               ?>;
        --h1-color-primary:      <?= ! empty(Customizer::get("toybox_headings_h1_color_primary"))           ? Customizer::get("toybox_headings_h1_color_primary")           : "#000000"                                                                                                                                                                                                         ?>;
        --h1-color-secondary:    <?= ! empty(Customizer::get("toybox_headings_h1_color_secondary"))         ? Customizer::get("toybox_headings_h1_color_secondary")         : "#000000"                                                                                                                                                                                                         ?>;
        --h2-size-full:          <?= ! empty(Customizer::get("toybox_headings_h2_size_full"))               ? Customizer::get("toybox_headings_h2_size_full")               : 2.25                                                                                                                                                                                                              ?>rem;
        --h2-size-medium:        <?= ! empty(Customizer::get("toybox_headings_h2_size_medium"))             ? Customizer::get("toybox_headings_h2_size_medium")             : 2                                                                                                                                                                                                                 ?>rem;
        --h2-size-small:         <?= ! empty(Customizer::get("toybox_headings_h2_size_small"))              ? Customizer::get("toybox_headings_h2_size_small")              : 1.75                                                                                                                                                                                                              ?>rem;
        --h2-weight:             <?= ! empty(Customizer::get("toybox_headings_h2_weight"))                  ? Customizer::get("toybox_headings_h2_weight")                  : 600                                                                                                                                                                                                               ?>;
        --h2-color-primary:      <?= ! empty(Customizer::get("toybox_headings_h2_color_primary"))           ? Customizer::get("toybox_headings_h2_color_primary")           : "#000000"                                                                                                                                                                                                         ?>;
        --h2-color-secondary:    <?= ! empty(Customizer::get("toybox_headings_h2_color_secondary"))         ? Customizer::get("toybox_headings_h2_color_secondary")         : "#000000"                                                                                                                                                                                                         ?>;
        --h3-size-full:          <?= ! empty(Customizer::get("toybox_headings_h3_size_full"))               ? Customizer::get("toybox_headings_h3_size_full")               : 2                                                                                                                                                                                                                 ?>rem;
        --h3-size-medium:        <?= ! empty(Customizer::get("toybox_headings_h3_size_medium"))             ? Customizer::get("toybox_headings_h3_size_medium")             : 1.75                                                                                                                                                                                                              ?>rem;
        --h3-size-small:         <?= ! empty(Customizer::get("toybox_headings_h3_size_small"))              ? Customizer::get("toybox_headings_h3_size_small")              : 1.5                                                                                                                                                                                                               ?>rem;
        --h3-weight:             <?= ! empty(Customizer::get("toybox_headings_h3_weight"))                  ? Customizer::get("toybox_headings_h3_weight")                  : 600                                                                                                                                                                                                               ?>;
        --h3-color-primary:      <?= ! empty(Customizer::get("toybox_headings_h3_color_primary"))           ? Customizer::get("toybox_headings_h3_color_primary")           : "#000000"                                                                                                                                                                                                         ?>;
        --h3-color-secondary:    <?= ! empty(Customizer::get("toybox_headings_h3_color_secondary"))         ? Customizer::get("toybox_headings_h3_color_secondary")         : "#000000"                                                                                                                                                                                                         ?>;
        --h4-size-full:          <?= ! empty(Customizer::get("toybox_headings_h4_size_full"))               ? Customizer::get("toybox_headings_h4_size_full")               : 1.75                                                                                                                                                                                                              ?>rem;
        --h4-size-medium:        <?= ! empty(Customizer::get("toybox_headings_h4_size_medium"))             ? Customizer::get("toybox_headings_h4_size_medium")             : 1.5                                                                                                                                                                                                               ?>rem;
        --h4-size-small:         <?= ! empty(Customizer::get("toybox_headings_h4_size_small"))              ? Customizer::get("toybox_headings_h4_size_small")              : 1.25                                                                                                                                                                                                              ?>rem;
        --h4-weight:             <?= ! empty(Customizer::get("toybox_headings_h4_weight"))                  ? Customizer::get("toybox_headings_h4_weight")                  : 600                                                                                                                                                                                                               ?>;
        --h4-color-primary:      <?= ! empty(Customizer::get("toybox_headings_h4_color_primary"))           ? Customizer::get("toybox_headings_h4_color_primary")           : "#000000"                                                                                                                                                                                                         ?>;
        --h4-color-secondary:    <?= ! empty(Customizer::get("toybox_headings_h4_color_secondary"))         ? Customizer::get("toybox_headings_h4_color_secondary")         : "#000000"                                                                                                                                                                                                         ?>;
        --h5-size-full:          <?= ! empty(Customizer::get("toybox_headings_h5_size_full"))               ? Customizer::get("toybox_headings_h5_size_full")               : 1.5                                                                                                                                                                                                               ?>rem;
        --h5-size-medium:        <?= ! empty(Customizer::get("toybox_headings_h5_size_medium"))             ? Customizer::get("toybox_headings_h5_size_medium")             : 1.25                                                                                                                                                                                                              ?>rem;
        --h5-size-small:         <?= ! empty(Customizer::get("toybox_headings_h5_size_small"))              ? Customizer::get("toybox_headings_h5_size_small")              : 1                                                                                                                                                                                                                 ?>rem;
        --h5-weight:             <?= ! empty(Customizer::get("toybox_headings_h5_weight"))                  ? Customizer::get("toybox_headings_h5_weight")                  : 600                                                                                                                                                                                                               ?>;
        --h5-color-primary:      <?= ! empty(Customizer::get("toybox_headings_h5_color_primary"))           ? Customizer::get("toybox_headings_h5_color_primary")           : "#000000"                                                                                                                                                                                                         ?>;
        --h5-color-secondary:    <?= ! empty(Customizer::get("toybox_headings_h5_color_secondary"))         ? Customizer::get("toybox_headings_h5_color_secondary")         : "#000000"                                                                                                                                                                                                         ?>;
        --h6-size-full:          <?= ! empty(Customizer::get("toybox_headings_h6_size_full"))               ? Customizer::get("toybox_headings_h6_size_full")               : 1.25                                                                                                                                                                                                              ?>rem;
        --h6-size-medium:        <?= ! empty(Customizer::get("toybox_headings_h6_size_medium"))             ? Customizer::get("toybox_headings_h6_size_medium")             : 1                                                                                                                                                                                                                 ?>rem;
        --h6-size-small:         <?= ! empty(Customizer::get("toybox_headings_h6_size_small"))              ? Customizer::get("toybox_headings_h6_size_small")              : 0.75                                                                                                                                                                                                              ?>rem;
        --h6-weight:             <?= ! empty(Customizer::get("toybox_headings_h6_weight"))                  ? Customizer::get("toybox_headings_h6_weight")                  : 600                                                                                                                                                                                                               ?>;
        --h6-color-primary:      <?= ! empty(Customizer::get("toybox_headings_h6_color_primary"))           ? Customizer::get("toybox_headings_h6_color_primary")           : "#000000"                                                                                                                                                                                                         ?>;
        --h6-color-secondary:    <?= ! empty(Customizer::get("toybox_headings_h6_color_secondary"))         ? Customizer::get("toybox_headings_h6_color_secondary")         : "#000000"                                                                                                                                                                                                         ?>;
        --title-family:          <?= ! empty(Customizer::get("toybox_text_settings_title_family"))          ? Customizer::get("toybox_text_settings_title_family")          : "system-ui, -apple-system, \"Segoe UI\", Roboto, \"Helvetica Neue\", \"Noto Sans\", \"Liberation Sans\", Arial, sans-serif, \"Apple Color Emoji\", \"Segoe UI Emoji\", \"Segoe UI Symbol\", \"Noto Color Emoji\"" ?>;
        --title-color-primary:   <?= ! empty(Customizer::get("toybox_text_settings_title_color_primary"))   ? Customizer::get("toybox_text_settings_title_color_primary")   : "#000000"                                                                                                                                                                                                         ?>;
        --title-color-secondary: <?= ! empty(Customizer::get("toybox_text_settings_title_color_secondary")) ? Customizer::get("toybox_text_settings_title_color_secondary") : "#000000"                                                                                                                                                                                                         ?>;
        --font-family:           <?= ! empty(Customizer::get("toybox_text_settings_body_family"))           ? Customizer::get("toybox_text_settings_body_family")           : "system-ui, -apple-system, \"Segoe UI\", Roboto, \"Helvetica Neue\", \"Noto Sans\", \"Liberation Sans\", Arial, sans-serif, \"Apple Color Emoji\", \"Segoe UI Emoji\", \"Segoe UI Symbol\", \"Noto Color Emoji\"" ?>;
        --font-size-full:        <?= ! empty(Customizer::get("toybox_text_settings_body_size_full"))        ? Customizer::get("toybox_text_settings_body_size_full")        : 1                                                                                                                                                                                                                 ?>;
        --font-size-medium:      <?= ! empty(Customizer::get("toybox_text_settings_body_size_medium"))      ? Customizer::get("toybox_text_settings_body_size_medium")      : 1                                                                                                                                                                                                                 ?>;
        --font-size-small:       <?= ! empty(Customizer::get("toybox_text_settings_body_size_small"))       ? Customizer::get("toybox_text_settings_body_size_small")       : 1                                                                                                                                                                                                                 ?>;
        --font-weight:           <?= ! empty(Customizer::get("toybox_text_settings_body_weight"))           ? Customizer::get("toybox_text_settings_body_weight")           : 400                                                                                                                                                                                                               ?>;
        --font-color-primary:    <?= ! empty(Customizer::get("toybox_text_settings_body_color_primary"))    ? Customizer::get("toybox_text_settings_body_color_primary")    : "#000000"                                                                                                                                                                                                         ?>;
        --font-color-secondary:  <?= ! empty(Customizer::get("toybox_text_settings_body_color_secondary"))  ? Customizer::get("toybox_text_settings_body_color_secondary")  : "#000000"                                                                                                                                                                                                         ?>;
    }
</style>